scripts/gitter-activity-notifier.coffee
Also added "unassigned" to issues regex.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/9)
=> feat(funnel): fix github username regex

external-scripts.json, package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/13)
=> Add scrumminator to glitch

package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/16)
=> chore(libs): update scrumminator

scripts/gitter-activity-notifier.coffee
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/17)
=> feat(funnel): group notifications by type

scripts/gitter-activity-notifier.coffee
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/18)
=> Fix broken notification stuff

scripts/gitter-activity-notifier.coffee
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/19)
=> fix(funnel): prevent submitting empty strings

package.json
We need to use version, it doesn't want to update otherwise.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/20)
=> chore(build): bump scrumminator version

package.json, scripts/example.coffee
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/24)
=> feat(core): add command to get package versions

scripts/gitter-activity-notifier.coffee
Closes #30
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/31)
=> feat(funnel): add option to spam single room

scripts/gitter-activity-notifier.coffee
wait for travis check on opened, synchronized, and reopened prs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/33)
=> feat(funnel): wait for travis check on prs

scripts/gitter-activity-notifier.coffee
remove `assigned,unassigned,labeled,unlabeled` from tracked pr actions
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/34)
=> feat(funnel): limit immediate pr messages

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/35)
=> feat(core): add some console output

.travis.yml, bin/hubot, package.json, scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/40)
=> Add issue names and PR demo links

scripts/gitter-activity-notifier.coffee
around names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/41)
=> refactor(funnel): add missing backward ticks

package.json, scripts/gitter-activity-notifier.coffee, scripts/glitch-py.js, scripts/glitch-py.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/42)
=> feat(core): post demo link to PR builds

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/43)
=> feat(PR): add checkbox for demo working

scripts/gitter-activity-notifier.coffee
Adds links to all demo pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/44)
=> feat(PR): add updated demo links in PR comment

scripts/check-pr-assignee.py, scripts/gitter-activity-notifier.coffee, scripts/glitch-py.js
leave a comment if it isn't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/45)
=> feat(PR): check if PR is assigned to someone

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/46)
=> fix(funnel): update short icon links

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/47)
=> feat(core): add mobile link

scripts/gitter-activity-notifier.coffee
Please, merge after https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2003#- is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/49)
=> add index-samples link to PR post

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/50)
=> fix(typo): mobile -> samples

external-scripts.json, package-lock.json, package.json
The old script of connecting to Azure doesn't work anymore - switched to a new one. Might need to patch throwing of `init` event in this one as well. See here: https://github.com/muffin-crusaders/hubot-azure-scripts/commits/master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/51)
=> switch azure-brain script

package-lock.json, scripts/gitter-activity-notifier.coffee
Fix PR demo links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/56)
=> chore: fix demo links

scripts/gitter-activity-notifier.coffee
Refactor glitch to use github webhooks
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/57)
=>  refactor glitch to use github webhooks

scripts/gitter-activity-notifier.coffee
also adds console logs on receiving from the webhook and sends a proper response after receiving it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/58)
=> Stop reacting to issue labeling

scripts/gitter-activity-notifier.coffee
:)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/59)
=> fix indenting

package-lock.json, package.json, scripts/gitter-activity-notifier.coffee, scripts/glitch-py.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/60)
=> Make glitch comments use js api

scripts/glitch-py.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/62)
=> i DON't even know why

scripts/glitch-py.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/64)
=> add check to check pr assignee

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/65)
=> glitch demand muffins for broken builds

scripts/gitter-activity-notifier.coffee
- stop excessive issue notifications and notify for priority labels
- notify pr creation for specific repos
- only comment builds for the fgpv repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/66)
=> fix labels, pr creation notifications, and pr build comments

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/67)
=> fix blank messages being sent by glitch

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/68)
=> fix label object reference

scripts/gitter-activity-notifier.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/muffin-crusaders/glitch/69)
=> fix blank glitch messages again
